language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ "$deps" = "low" ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat