language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
  - php: 5.5

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer instal

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat